"""Build a real macOS application bundle.

Run from a terminal, this is not an app as far as macOS is concerned. It has no
identity, so the camera permission is granted to Terminal or iTerm and shows up
under that name; it has no Info.plist, so the permission prompt cannot explain
itself; it puts an icon in the Dock it has no use for; and it dies with the
window you started it from.

A bundle fixes all four, and it is a directory with a plist in it -- no build
step, no packaging tool, no several hundred megabytes of vendored interpreter.
The launcher inside execs the interpreter this was installed into, so the app
and the ``posture-guard`` command stay the same program and cannot drift apart.

What the keys are for:

``LSUIElement``
    Menu bar only, no Dock icon and no window. Correct for something that lives
    in the corner of the screen all day.
``NSCameraUsageDescription``
    The sentence macOS shows when it asks. Without it a bundled app is not
    permitted to ask at all.
``NSCameraUseContinuityCameraDeviceType``
    Lets an iPhone be recognised as what it is instead of as a generic external
    camera, which is what the deprecation warning in the logs is about.
"""

from __future__ import annotations

import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

from . import __version__

BUNDLE_NAME = "PostureGuard"
BUNDLE_ID = "nl.emielvanlieshout.posture-guard"

CAMERA_REASON = (
    "posture-guard watches your posture through the camera. The video is turned "
    "into a handful of numbers on this Mac and discarded; nothing is recorded, "
    "saved or uploaded."
)

LAUNCHER = """#!/bin/sh
# Generated by `posture-guard install-app`. Edit the source, not this.
#
# Finder starts an app with almost no environment and the working directory set
# to /, so the interpreter is referenced absolutely.
PY="{python}"
LOG="$HOME/Library/Logs/posture-guard.log"

# Pinned to whatever `install-app` was running as, because that is the
# architecture the packages were built for. A universal Python inherits its
# architecture from whatever started it, so launchd can hand you Rosetta even
# when the terminal runs native -- and then the first compiled import dies and
# the app is gone before it draws anything.
ARCH="{arch}"
if [ -x /usr/bin/arch ]; then
    RUN="/usr/bin/arch -$ARCH $PY"
else
    RUN="$PY"
fi

# Run this file directly from a terminal and the output stays in front of you.
# Redirecting unconditionally would mean the one command that could show you
# what the app sees hides it in a log file, which is exactly the wrong way
# round when the app will not start.
if [ -t 1 ]; then
    exec $RUN -m posture_guard run "$@"
fi

mkdir -p "$(dirname "$LOG")"
# A dated marker, so the log distinguishes "never launched" from "launched and
# then died" -- which look identical from the outside.
printf '\n=== %s starting ===\n' "$(date '+%Y-%m-%d %H:%M:%S')" >>"$LOG"
exec $RUN -m posture_guard run >>"$LOG" 2>&1
"""


def log_path():
    return Path.home() / "Library" / "Logs" / "posture-guard.log"


def describe_install(bundle: Path | None = None) -> list[str]:
    """What is actually on disk, for `posture-guard doctor`.

    An app that will not start looks the same as an app that started and hid
    itself, so the point here is to separate those: does the bundle exist, does
    the interpreter it names still exist, and did anything reach the log.
    """
    bundle = Path(bundle) if bundle else default_destination()
    lines = []

    if not bundle.exists():
        return [f"not installed (run `posture-guard install-app`)"]

    lines.append(str(bundle))
    launcher = bundle / "Contents" / "MacOS" / BUNDLE_NAME
    if not launcher.exists():
        lines.append("launcher missing; rebuild with `posture-guard install-app`")
        return lines
    if not launcher.stat().st_mode & stat.S_IXUSR:
        lines.append("launcher is not executable; rebuild it")

    python = pinned_arch = ""
    for line in launcher.read_text().splitlines():
        if line.startswith('PY="'):
            python = line[4:].rstrip('"')
        elif line.startswith('ARCH="'):
            pinned_arch = line[6:].rstrip('"')
    if pinned_arch:
        import platform

        here = platform.machine()
        note = "" if pinned_arch == here else f"   (this shell is {here})"
        lines.append(f"pinned to {pinned_arch}{note}")
    if python:
        exists = Path(python).exists()
        lines.append(f"interpreter {python}" + ("" if exists else "   MISSING"))
        if not exists:
            lines.append("that virtualenv is gone; rebuild with `posture-guard install-app`")

    log = log_path()
    if not log.exists():
        lines.append("no log yet, so it has never started")
    else:
        tail = log.read_text(errors="replace").splitlines()[-8:]
        lines.append(f"last lines of {log}:")
        lines.extend(f"  {line}" for line in tail if line.strip())

    lines.append(f"to see it start, run it yourself: {launcher}")
    return lines


class BundleError(RuntimeError):
    pass


def default_destination() -> Path:
    """~/Applications, which needs no admin rights and is indexed by Spotlight."""
    return Path.home() / "Applications" / f"{BUNDLE_NAME}.app"


def build_app(
    destination: Path | None = None,
    *,
    python: str | None = None,
    version: str = __version__,
    arch: str | None = None,
) -> Path:
    """Write the bundle, replacing any previous one. Returns its path."""
    import platform

    destination = Path(destination) if destination else default_destination()
    python = python or sys.executable
    # This process imported the compiled packages to get here, so whatever it is
    # running as is the architecture that works.
    arch = arch or platform.machine()
    if not destination.name.endswith(".app"):
        destination = destination / f"{BUNDLE_NAME}.app"

    contents = destination / "Contents"
    macos = contents / "MacOS"

    if destination.exists():
        if not (destination / "Contents" / "Info.plist").exists():
            raise BundleError(
                f"{destination} exists and is not an app bundle; refusing to remove it"
            )
        shutil.rmtree(destination)

    macos.mkdir(parents=True)
    (contents / "Resources").mkdir(exist_ok=True)

    plist = {
        "CFBundleName": BUNDLE_NAME,
        "CFBundleDisplayName": "posture-guard",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": BUNDLE_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "12.0",
        "LSUIElement": True,
        "NSHighResolutionCapable": True,
        "NSCameraUsageDescription": CAMERA_REASON,
        "NSCameraUseContinuityCameraDeviceType": True,
    }
    with (contents / "Info.plist").open("wb") as handle:
        plistlib.dump(plist, handle)

    launcher = macos / BUNDLE_NAME
    launcher.write_text(LAUNCHER.format(python=python, arch=arch))
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    return destination


def register(bundle: Path) -> None:
    """Nudge Launch Services, so the app is usable without logging out first."""
    lsregister = (
        "/System/Library/Frameworks/CoreServices.framework/Frameworks/"
        "LaunchServices.framework/Support/lsregister"
    )
    if Path(lsregister).exists():
        subprocess.run(  # noqa: S603 - fixed system path
            [lsregister, "-f", str(bundle)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )


def login_item_script(bundle: Path, add: bool = True) -> str:
    """AppleScript adding or removing the bundle as a login item."""
    if add:
        return (
            'tell application "System Events" to make login item at end with properties '
            f'{{path:"{bundle}", hidden:true}}'
        )
    return (
        'tell application "System Events" to delete login item '
        f'"{bundle.stem}"'
    )


def set_login_item(bundle: Path, add: bool = True) -> bool:
    osascript = shutil.which("osascript")
    if not osascript:
        return False
    result = subprocess.run(  # noqa: S603 - fixed binary
        [osascript, "-e", login_item_script(bundle, add)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.returncode == 0
