"""Build a real macOS application bundle.

Run from a terminal, this is not an app as far as macOS is concerned. It has no
identity, so the camera permission is granted to Terminal or iTerm and shows up
under that name; it has no Info.plist, so the permission prompt cannot explain
itself; it puts an icon in the Dock it has no use for; and it dies with the
window you started it from.

A bundle fixes all four, and it is a directory with a plist in it -- no build
step, no packaging tool, no several hundred megabytes of vendored interpreter.
The launcher inside execs the interpreter this was installed into, so the app
and the ``posture-guard`` command stay the same program and cannot drift apart.

What the keys are for:

``LSUIElement``
    Menu bar only, no Dock icon and no window. Correct for something that lives
    in the corner of the screen all day.
``NSCameraUsageDescription``
    The sentence macOS shows when it asks. Without it a bundled app is not
    permitted to ask at all.
``NSCameraUseContinuityCameraDeviceType``
    Lets an iPhone be recognised as what it is instead of as a generic external
    camera, which is what the deprecation warning in the logs is about.

Why there is a compiled stub in here
------------------------------------
The bundle's executable has to be a real Mach-O binary. With a shell script in
that slot the app launches perfectly well, but macOS never associates the
process with this Info.plist -- the running executable is an interpreter living
somewhere else entirely -- so TCC has no usage description to show, and the
camera prompt silently never appears. The log reads "asking macOS for camera
access" and then nothing at all, for ever.

So the executable is twenty lines of C that hand straight over to the script,
which keeps the architecture pinning and the logging in one editable place. If
no compiler is available the script goes back in the executable slot and
`install-app` says what that costs.
"""

from __future__ import annotations

import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

from . import __version__

BUNDLE_NAME = "PostureGuard"
BUNDLE_ID = "nl.emielvanlieshout.posture-guard"

CAMERA_REASON = (
    "posture-guard watches your posture through the camera. The video is turned "
    "into a handful of numbers on this Mac and discarded; nothing is recorded, "
    "saved or uploaded."
)

STUB_SOURCE = r"""
/* The bundle executable. Launch Services will start a shell script here quite
   happily, but macOS only associates a process with its Info.plist when the
   executable is a Mach-O binary in the bundle -- and without that association
   TCC has no camera usage description to present, so the prompt never appears.
   This exists to be that binary. It does nothing but exec the script. */
#include <libgen.h>
#include <limits.h>
#include <mach-o/dyld.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
    char executable[PATH_MAX];
    uint32_t size = sizeof(executable);
    if (_NSGetExecutablePath(executable, &size) != 0) {
        fprintf(stderr, "posture-guard: could not locate the bundle\n");
        return 1;
    }

    char resolved[PATH_MAX];
    if (realpath(executable, resolved) == NULL) {
        strncpy(resolved, executable, sizeof(resolved) - 1);
        resolved[sizeof(resolved) - 1] = '\0';
    }

    /* .../Contents/MacOS/PostureGuard -> .../Contents */
    char macos_copy[PATH_MAX];
    strncpy(macos_copy, resolved, sizeof(macos_copy) - 1);
    macos_copy[sizeof(macos_copy) - 1] = '\0';
    char *macos = dirname(macos_copy);

    char contents_copy[PATH_MAX];
    strncpy(contents_copy, macos, sizeof(contents_copy) - 1);
    contents_copy[sizeof(contents_copy) - 1] = '\0';
    char *contents = dirname(contents_copy);

    char script[PATH_MAX];
    snprintf(script, sizeof(script), "%s/Resources/launch.sh", contents);

    char **args = calloc((size_t)argc + 3, sizeof(char *));
    if (args == NULL) {
        return 1;
    }
    args[0] = "sh";
    args[1] = script;
    for (int i = 1; i < argc; i++) {
        args[i + 1] = argv[i];
    }
    args[argc + 1] = NULL;

    execv("/bin/sh", args);
    fprintf(stderr, "posture-guard: could not run %s\n", script);
    return 1;
}
"""

LAUNCHER = """#!/bin/sh
# Generated by `posture-guard install-app`. Edit the source, not this.
#
# Finder starts an app with almost no environment and the working directory set
# to /, so the interpreter is referenced absolutely.
PY="{python}"
LOG="$HOME/Library/Logs/posture-guard.log"

# Pinned to whatever `install-app` was running as, because that is the
# architecture the packages were built for. A universal Python inherits its
# architecture from whatever started it, so launchd can hand you Rosetta even
# when the terminal runs native -- and then the first compiled import dies and
# the app is gone before it draws anything.
ARCH="{arch}"
if [ -x /usr/bin/arch ]; then
    RUN="/usr/bin/arch -$ARCH $PY"
else
    RUN="$PY"
fi

# Unbuffered. Writing to a file rather than a terminal, Python block-buffers
# stdout, so output sits in memory until the buffer fills or the process exits.
# A log that only tells you what happened once the app has stopped is no use for
# working out why it stopped.
export PYTHONUNBUFFERED=1

# Run this file directly from a terminal and the output stays in front of you.
# Redirecting unconditionally would mean the one command that could show you
# what the app sees hides it in a log file, which is exactly the wrong way
# round when the app will not start.
if [ -t 1 ]; then
    exec $RUN -m posture_guard run "$@"
fi

mkdir -p "$(dirname "$LOG")"
# A dated marker, so the log distinguishes "never launched" from "launched and
# then died" -- which look identical from the outside.
printf '\n=== %s starting ===\n' "$(date '+%Y-%m-%d %H:%M:%S')" >>"$LOG"
exec $RUN -m posture_guard run >>"$LOG" 2>&1
"""


def log_path():
    return Path.home() / "Library" / "Logs" / "posture-guard.log"


def describe_install(bundle: Path | None = None) -> list[str]:
    """What is actually on disk, for `posture-guard doctor`.

    An app that will not start looks the same as an app that started and hid
    itself, so the point here is to separate those: does the bundle exist, does
    the interpreter it names still exist, and did anything reach the log.
    """
    bundle = Path(bundle) if bundle else default_destination()
    lines = []

    if not bundle.exists():
        return [f"not installed (run `posture-guard install-app`)"]

    lines.append(str(bundle))
    launcher = bundle / "Contents" / "MacOS" / BUNDLE_NAME
    if not launcher.exists():
        lines.append("launcher missing; rebuild with `posture-guard install-app`")
        return lines
    if not launcher.stat().st_mode & stat.S_IXUSR:
        lines.append("launcher is not executable; rebuild it")

    script = bundle / "Contents" / "Resources" / "launch.sh"
    settings_from = script if script.exists() else launcher
    python = pinned_arch = ""
    for line in settings_from.read_text(errors="replace").splitlines():
        if line.startswith('PY="'):
            python = line[4:].rstrip('"')
        elif line.startswith('ARCH="'):
            pinned_arch = line[6:].rstrip('"')
    lines.append(f"executable is a {executable_kind(bundle)}")
    if executable_kind(bundle) == "shell script":
        lines.append("a script here cannot show the camera prompt; install Xcode command")
        lines.append("line tools (xcode-select --install) and run install-app again")
    if pinned_arch:
        import platform

        here = platform.machine()
        note = "" if pinned_arch == here else f"   (this shell is {here})"
        lines.append(f"pinned to {pinned_arch}{note}")
    if python:
        exists = Path(python).exists()
        lines.append(f"interpreter {python}" + ("" if exists else "   MISSING"))
        if not exists:
            lines.append("that virtualenv is gone; rebuild with `posture-guard install-app`")

    log = log_path()
    if not log.exists():
        lines.append("no log yet, so it has never started")
    else:
        tail = log.read_text(errors="replace").splitlines()[-8:]
        lines.append(f"last lines of {log}:")
        lines.extend(f"  {line}" for line in tail if line.strip())

    lines.append(f"to see it start, run it yourself: {launcher}")
    return lines


class BundleError(RuntimeError):
    pass


def default_destination() -> Path:
    """~/Applications, which needs no admin rights and is indexed by Spotlight."""
    return Path.home() / "Applications" / f"{BUNDLE_NAME}.app"


def build_app(
    destination: Path | None = None,
    *,
    python: str | None = None,
    version: str = __version__,
    arch: str | None = None,
    compile_stub: bool = True,
) -> Path:
    """Write the bundle, replacing any previous one. Returns its path."""
    import platform

    destination = Path(destination) if destination else default_destination()
    python = python or sys.executable
    # This process imported the compiled packages to get here, so whatever it is
    # running as is the architecture that works.
    arch = arch or platform.machine()
    if not destination.name.endswith(".app"):
        destination = destination / f"{BUNDLE_NAME}.app"

    contents = destination / "Contents"
    macos = contents / "MacOS"

    if destination.exists():
        if not (destination / "Contents" / "Info.plist").exists():
            raise BundleError(
                f"{destination} exists and is not an app bundle; refusing to remove it"
            )
        shutil.rmtree(destination)

    macos.mkdir(parents=True)
    (contents / "Resources").mkdir(exist_ok=True)

    plist = {
        "CFBundleName": BUNDLE_NAME,
        "CFBundleDisplayName": "posture-guard",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": BUNDLE_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "12.0",
        "LSUIElement": True,
        "NSHighResolutionCapable": True,
        "NSCameraUsageDescription": CAMERA_REASON,
        "NSCameraUseContinuityCameraDeviceType": True,
    }
    with (contents / "Info.plist").open("wb") as handle:
        plistlib.dump(plist, handle)

    # The script keeps the architecture pinning and the logging, in one place
    # that stays readable and editable.
    script = contents / "Resources" / "launch.sh"
    script.write_text(LAUNCHER.format(python=python, arch=arch))
    _make_executable(script)

    executable = macos / BUNDLE_NAME
    if not (compile_stub and _compile_stub(executable, arch)):
        # No compiler: the script goes in the executable slot, which launches
        # but leaves the camera prompt unable to appear. install-app says so.
        shutil.copyfile(script, executable)
    _make_executable(executable)

    return destination


def _make_executable(path: Path) -> None:
    path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def have_compiler() -> bool:
    return bool(shutil.which("clang") or shutil.which("cc"))


def _compile_stub(destination: Path, arch: str) -> bool:
    """Build the Mach-O executable. False when there is no compiler to do it."""
    compiler = shutil.which("clang") or shutil.which("cc")
    if compiler is None or sys.platform != "darwin":
        return False
    try:
        result = subprocess.run(  # noqa: S603 - fixed compiler, literal source
            [compiler, "-arch", arch, "-O2", "-o", str(destination), "-x", "c", "-"],
            input=STUB_SOURCE,
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0 and destination.exists()


def executable_kind(bundle: Path) -> str:
    """Whether the bundle executable is a compiled binary or a script."""
    executable = Path(bundle) / "Contents" / "MacOS" / BUNDLE_NAME
    try:
        head = executable.read_bytes()[:4]
    except OSError:
        return "missing"
    if head.startswith(b"#!"):
        return "shell script"
    # Mach-O magic, either endianness, thin or fat.
    if head in (b"\xcf\xfa\xed\xfe", b"\xce\xfa\xed\xfe", b"\xca\xfe\xba\xbe"):
        return "compiled stub"
    return "unknown"


def register(bundle: Path) -> None:
    """Nudge Launch Services, so the app is usable without logging out first."""
    lsregister = (
        "/System/Library/Frameworks/CoreServices.framework/Frameworks/"
        "LaunchServices.framework/Support/lsregister"
    )
    if Path(lsregister).exists():
        subprocess.run(  # noqa: S603 - fixed system path
            [lsregister, "-f", str(bundle)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )


def login_item_script(bundle: Path, add: bool = True) -> str:
    """AppleScript adding or removing the bundle as a login item."""
    if add:
        return (
            'tell application "System Events" to make login item at end with properties '
            f'{{path:"{bundle}", hidden:true}}'
        )
    return (
        'tell application "System Events" to delete login item '
        f'"{bundle.stem}"'
    )


def set_login_item(bundle: Path, add: bool = True) -> bool:
    osascript = shutil.which("osascript")
    if not osascript:
        return False
    result = subprocess.run(  # noqa: S603 - fixed binary
        [osascript, "-e", login_item_script(bundle, add)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.returncode == 0
