"""Build a real macOS application bundle.

Run from a terminal, this is not an app as far as macOS is concerned. It has no
identity, so the camera permission is granted to Terminal or iTerm and shows up
under that name; it has no Info.plist, so the permission prompt cannot explain
itself; it puts an icon in the Dock it has no use for; and it dies with the
window you started it from.

A bundle fixes all four, and it is a directory with a plist in it -- no build
step, no packaging tool, no several hundred megabytes of vendored interpreter.
The launcher inside execs the interpreter this was installed into, so the app
and the ``posture-guard`` command stay the same program and cannot drift apart.

What the keys are for:

``LSUIElement``
    Menu bar only, no Dock icon and no window. Correct for something that lives
    in the corner of the screen all day.
``NSCameraUsageDescription``
    The sentence macOS shows when it asks. Without it a bundled app is not
    permitted to ask at all.
``NSCameraUseContinuityCameraDeviceType``
    Lets an iPhone be recognised as what it is instead of as a generic external
    camera, which is what the deprecation warning in the logs is about.
"""

from __future__ import annotations

import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

from . import __version__

BUNDLE_NAME = "PostureGuard"
BUNDLE_ID = "nl.emielvanlieshout.posture-guard"

CAMERA_REASON = (
    "posture-guard watches your posture through the camera. The video is turned "
    "into a handful of numbers on this Mac and discarded; nothing is recorded, "
    "saved or uploaded."
)

LAUNCHER = """#!/bin/sh
# Generated by `posture-guard install-app`. Edit the source, not this.
#
# Finder starts an app with almost no environment and the working directory set
# to /, so the interpreter is referenced absolutely. Output goes to a log file
# because a bundle has no terminal to complain into.
LOG="$HOME/Library/Logs/posture-guard.log"
mkdir -p "$(dirname "$LOG")"
exec "{python}" -m posture_guard run >>"$LOG" 2>&1
"""


class BundleError(RuntimeError):
    pass


def default_destination() -> Path:
    """~/Applications, which needs no admin rights and is indexed by Spotlight."""
    return Path.home() / "Applications" / f"{BUNDLE_NAME}.app"


def build_app(
    destination: Path | None = None,
    *,
    python: str | None = None,
    version: str = __version__,
) -> Path:
    """Write the bundle, replacing any previous one. Returns its path."""
    destination = Path(destination) if destination else default_destination()
    python = python or sys.executable
    if not destination.name.endswith(".app"):
        destination = destination / f"{BUNDLE_NAME}.app"

    contents = destination / "Contents"
    macos = contents / "MacOS"

    if destination.exists():
        if not (destination / "Contents" / "Info.plist").exists():
            raise BundleError(
                f"{destination} exists and is not an app bundle; refusing to remove it"
            )
        shutil.rmtree(destination)

    macos.mkdir(parents=True)
    (contents / "Resources").mkdir(exist_ok=True)

    plist = {
        "CFBundleName": BUNDLE_NAME,
        "CFBundleDisplayName": "posture-guard",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": BUNDLE_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "12.0",
        "LSUIElement": True,
        "NSHighResolutionCapable": True,
        "NSCameraUsageDescription": CAMERA_REASON,
        "NSCameraUseContinuityCameraDeviceType": True,
    }
    with (contents / "Info.plist").open("wb") as handle:
        plistlib.dump(plist, handle)

    launcher = macos / BUNDLE_NAME
    launcher.write_text(LAUNCHER.format(python=python))
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    return destination


def register(bundle: Path) -> None:
    """Nudge Launch Services, so the app is usable without logging out first."""
    lsregister = (
        "/System/Library/Frameworks/CoreServices.framework/Frameworks/"
        "LaunchServices.framework/Support/lsregister"
    )
    if Path(lsregister).exists():
        subprocess.run(  # noqa: S603 - fixed system path
            [lsregister, "-f", str(bundle)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )


def login_item_script(bundle: Path, add: bool = True) -> str:
    """AppleScript adding or removing the bundle as a login item."""
    if add:
        return (
            'tell application "System Events" to make login item at end with properties '
            f'{{path:"{bundle}", hidden:true}}'
        )
    return (
        'tell application "System Events" to delete login item '
        f'"{bundle.stem}"'
    )


def set_login_item(bundle: Path, add: bool = True) -> bool:
    osascript = shutil.which("osascript")
    if not osascript:
        return False
    result = subprocess.run(  # noqa: S603 - fixed binary
        [osascript, "-e", login_item_script(bundle, add)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.returncode == 0
